<script setup>
import { useRouter } from 'vue-router'

const router = useRouter()
</script>

<template>
  <div class="min-h-screen bg-[#070b14] text-slate-300 py-12 px-6 sm:px-12 lg:px-24 selection:bg-sky-500/30">
    <div class="max-w-4xl mx-auto space-y-8">
      <!-- Header -->
      <header class="border-b border-slate-800 pb-8 flex items-center justify-between">
        <div>
          <h1 class="text-3xl font-bold text-white tracking-tight mb-2">Terms of Service</h1>
          <p class="text-sm text-slate-500">Effective Date: October 2026</p>
        </div>
        <button 
          @click="router.push('/')" 
          class="flex items-center space-x-2 px-4 py-2 bg-slate-900 border border-slate-700 hover:border-sky-500 hover:text-sky-400 rounded-lg text-sm font-medium transition-colors"
        >
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path></svg>
          <span>Back to Dashboard</span>
        </button>
      </header>

      <!-- Content -->
      <article class="prose prose-invert prose-slate max-w-none space-y-8">
        
        <section>
          <h2 class="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
          <p class="leading-relaxed">
            By accessing or using the Actura platform ("Actura", "Platform", "Service"), you agree to be bound by these Terms of Service. Actura is an enterprise-grade actuarial valuation and risk modeling software designed for institutional use. If you do not agree to all terms, do not access the platform.
          </p>
        </section>

        <section>
          <h2 class="text-xl font-semibold text-white mb-3">2. Financial & Actuarial Disclaimer (CRITICAL)</h2>
          <div class="bg-red-500/10 border border-red-500/20 rounded-lg p-5 text-red-200/90 leading-relaxed space-y-3">
            <p><strong>Actura is an analytical support tool, not a certified advisory service.</strong></p>
            <p>
              The platform executes complex mathematical models, stochastic projections (including Monte Carlo and Vasicek ESG simulations), and IFRS 17 estimations based on user-provided inputs. 
            </p>
            <p>
              Under no circumstances do the outputs, trajectories, reserves, or sensitivities generated by Actura constitute formal financial guarantees, certified actuarial opinions, investment advice, or regulatory compliance binding. You, the user, retain absolute responsibility for verifying all calculations prior to making financial, reserving, or capital allocation decisions.
            </p>
          </div>
        </section>

        <section>
          <h2 class="text-xl font-semibold text-white mb-3">3. Intellectual Property</h2>
          <p class="leading-relaxed">
            The Actura software, including but not limited to its valuation engine algorithms, node-based blueprint rendering architecture, UI/UX designs, and the Actura mascot/branding, remain the exclusive intellectual property of Actura Inc. and its licensors. You are granted a limited, non-exclusive license to utilize the platform in accordance with your subscription tier.
          </p>
        </section>

        <section>
          <h2 class="text-xl font-semibold text-white mb-3">4. Acceptable Use</h2>
          <p class="leading-relaxed">
            You agree not to misuse the Actura platform. Prohibited actions include, but are not limited to:
          </p>
          <ul class="list-disc pl-5 mt-2 space-y-1">
            <li>Reverse-engineering the valuation engine or logic builder.</li>
            <li>Flooding the API with excessive, automated requests beyond standard batch processing limits.</li>
            <li>Attempting to bypass security, licensing, or resource limits.</li>
          </ul>
        </section>

        <section>
          <h2 class="text-xl font-semibold text-white mb-3">5. Limitation of Liability</h2>
          <p class="leading-relaxed">
            To the maximum extent permitted by applicable law, Actura Inc. and its creators shall not be held liable for any direct, indirect, incidental, special, or consequential damages resulting from the use or inability to use the platform. This includes, but is not limited to, financial insolvency, regulatory fines, data loss, or missed revenue stemming from reliance on platform outputs.
          </p>
        </section>

      </article>

      <footer class="pt-8 border-t border-slate-800 text-sm text-slate-500 text-center">
        © 2026 Actura. All rights reserved.
      </footer>
    </div>
  </div>
</template>
